name: 'Pull Request'

on:
  pull_request:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run clippy
        run: cargo clippy

      - name: Run fmt check
        run: cargo fmt --check

      - name: Run check
        run: cargo check
